import Head from 'next/head'
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import Image from 'next/image'
import Header from '../components/header'
import styles from '../styles/Home.module.css'
import { useTranslation } from "next-i18next";


export default function Home() {
  const { t } = useTranslation("common");

  return (
    <div className={styles.container}>
      <Head>
        <title>Pursatly Yorish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div >
        <div className={styles.main}>
          <h1>PURSATLY ÝÖRIŞ</h1>
          <p>
            {t("common.heroDesc")}
          </p>
        </div>

        <div className={styles.about}>
          <div>
            <h3>{t("aboutSection.title")}</h3>
            <p>
              {t("aboutSection.desc1")}
            </p>
            <p>
              {t("aboutSection.desc2")}
            </p>
            <p>
              {t("aboutSection.desc3")}
            </p>
            <Image
              src="/glass-greenhouse (1).png"
              width={906}
              height={456}
              alt=""
            />
          </div>
          <div>
            <h3>- {t("aboutSection.important")}</h3>
            <p>
              - {t("aboutSection.item1")}
            </p>
            <p>
              - {t("aboutSection.item2")}
            </p>
            <p>
              - {t("aboutSection.item3")}
            </p>
            <div className={styles.secondImg}>
              <Image
                src="/Frame 2.png"
                width={487}
                height={418}
                alt=""
              />
            </div>

          </div>
        </div>

        <div className={styles.animation}>
          <div className={styles.firstImg}>
            <div>
              <Image src="/img1.png" layout="fill" alt=""/>
              <div>
                <h3>Microchip</h3>
                <p>Лорем ипсум долор сит амет, ин еос мелиус бонорум молестиае,
                  еос ан деленити цонституам. Ад хомеро сцрипторем усу. </p>
              </div>
            </div>
            <div className={styles.backDrop}></div>

          </div>
          <div className={styles.secondImg}>
            <div>
              <Image src="/img2.png" layout="fill" alt=""/>
              <div>
                <h3>Microchip</h3>
                <p>Лорем ипсум долор сит амет, ин еос мелиус бонорум молестиае,
                  еос ан деленити цонституам. Ад хомеро сцрипторем усу. </p>
              </div>
            </div>
            <div className={styles.backDrop}></div>
          </div>
          <div className={styles.thirdImg}>
            <div>
              <Image src="/img3.png" layout="fill" alt=""/>
              <div>
                <h3>Microchip</h3>
                <p>Лорем ипсум долор сит амет, ин еос мелиус бонорум молестиае,
                  еос ан деленити цонституам. Ад хомеро сцрипторем усу. </p>
              </div>
            </div>
            <div className={styles.backDrop}></div>
          </div>
          <div className={styles.fourthImg}>
            <div>
              <Image src="/img4.png" layout="fill" alt=""/>
              <div>
                <h3>Microchip</h3>
                <p>Лорем ипсум долор сит амет, ин еос мелиус бонорум молестиае,
                  еос ан деленити цонституам. Ад хомеро сцрипторем усу. </p>
              </div>
            </div>
            {/* <div className={styles.backDrop}></div> */}
          </div>
          <div className={styles.mainImg}>
            <div>
              <Image src="/img0.png" layout="fill" alt=""/>
              <div>
                <h3>Microchip</h3>
                <p>Лорем ипсум долор сит амет, ин еос мелиус бонорум молестиае,
                  еос ан деленити цонституам. Ад хомеро сцрипторем усу. </p>
              </div>
            </div>
            {/* <div className={styles.backDrop}></div> */}
          </div>
        </div>
      </div>


    </div>
  )
}

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});