import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <div >
          <div className={styles.main}>
                <h1>PURSATLY ÝÖRIŞ</h1>
                <p>
                  один из лидеров рынка, специализирующийся на электро-технике и электронике. 
                  Наши устойчивые парнерские связи, от большего круга мировых производителей, 
                  позволяет нам предложить нашим клиентам надежные и устройчивые силовые модули, 
                  чипы/микрочипы, UC's DC-DC конверторы.
                </p>
          </div>

          <div className={styles.about}>
                <div>
                    <h3>О компании</h3>
                    <p>
                        Индивидуальное Предприятие “Pursatly Ýöriş” было основано в 2020 году. 
                        Компания обладает необходимыми знаниями и опытом, чтобы предложить 
                        Вам наилучшие решения с сфере техники, электроники и электротехники. 
                    </p>
                    <p>
                        Наша способна оценить нынешние и будущие потребности Вашего бизнеса и проекта, 
                        предоставить несколько оптимальных вариантов, ускорить и оптимизировать работу Вашего предприятия.
                    </p>
                    <p>
                        Мы сотрудничаем с государственными и частными компаниями, министрествами и организациями, а также 
                        имеем доверительные парнерские отношения с иностранными производителями.
                    </p>
                    <Image 
                        src="/glass-greenhouse (1).png"
                        width={906}
                        height={456}
                      />
                </div>
                <div>
                  <h3>Для нас важны:</h3>
                  <p>
                    Продуктивность
                  </p>
                  <p>
                    Современность
                  </p>
                  <p> 
                      Надежность
                  </p>
                  <div className={styles.secondImg}>
                    <Image 
                        src="/Frame 2.png"
                        width={487}
                        height={418}
                    />
                  </div>
                 
                </div>
          </div>

          <div className={styles.animation}>
                <div className={styles.firstImg}>
                    <div>
                        <Image src="/img1.png" layout="fill" />
                        <div>
                            <h3>Microchip</h3>
                            <p>Лорем ипсум долор сит амет, ин еос мелиус бонорум молестиае, 
                              еос ан деленити цонституам. Ад хомеро сцрипторем усу. </p>
                        </div>
                    </div>
                    <div className={styles.backDrop}></div>

                </div>
                <div className={styles.secondImg}>
                    <div>
                        <Image src="/img2.png" layout="fill" />
                        <div>
                            <h3>Microchip</h3>
                            <p>Лорем ипсум долор сит амет, ин еос мелиус бонорум молестиае, 
                              еос ан деленити цонституам. Ад хомеро сцрипторем усу. </p>
                        </div>
                    </div>
                    <div className={styles.backDrop}></div>
                </div>
                <div className={styles.thirdImg}>
                    <div>
                        <Image src="/img3.png" layout="fill" />
                        <div>
                            <h3>Microchip</h3>
                            <p>Лорем ипсум долор сит амет, ин еос мелиус бонорум молестиае, 
                              еос ан деленити цонституам. Ад хомеро сцрипторем усу. </p>
                        </div>
                    </div>
                    <div className={styles.backDrop}></div>
                </div>
                <div className={styles.fourthImg}>
                    <div>
                        <Image src="/img4.png" layout="fill" />
                        <div>
                            <h3>Microchip</h3>
                            <p>Лорем ипсум долор сит амет, ин еос мелиус бонорум молестиае, 
                              еос ан деленити цонституам. Ад хомеро сцрипторем усу. </p>
                        </div>
                    </div>
                    {/* <div className={styles.backDrop}></div> */}
                </div>
                <div className={styles.mainImg}>
                    <div>
                        <Image src="/img0.png" layout="fill" />
                        <div>
                            <h3>Microchip</h3>
                            <p>Лорем ипсум долор сит амет, ин еос мелиус бонорум молестиае, 
                              еос ан деленити цонституам. Ад хомеро сцрипторем усу. </p>
                        </div>
                    </div>
                    {/* <div className={styles.backDrop}></div> */}
                </div>
          </div>
      </div>
     

    </div>
  )
}
